apiVersion: v2
name: sb-send-sync
description: A stress test chart with sync message send to SB
version: 0.1.1
appVersion: v0.1
annotations:
  stressTest: 'true'  # enable auto-discovery of this test via `find-all-stress-packages.ps1`
  example: 'true'  # enable auto-discovery filtering `find-all-stress-packages.ps1 -filters @{example='true'}`
  namespace: 'examples'

dependencies:
- name: stress-test-addons
  version: 0.1.6
  repository: https://stresstestcharts.blob.core.windows.net/helm/
